### ISSUE TITLE
can't run the image

### ISSUE THREAD

**Issue by humanperzeus** [rcribbs/arch-vnc-headless#2]
can you provide a running command? I cannot run this image

**Comment by rcribbs** [comment]
I think the image was subject to some changes in vncserver that broke the start script. I've updated it please use > v1.0.1 and see if it will run correctly.

For reference here's an example of how I might run it:
`docker run -p 5901:5901 --name my-arch-vnc -e VNC_PASSWORD="secret" -e CUSTOM_RESOLUTIONS="2048x1536,544x662" rcribbs/arch-vnc-headless`
